name: Build Android
on: [workflow_call]
jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: prepare rust targets
        run: rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android
      - name: build
        run: ./gradlew assembleDebug assembleRelease --info --parallel
      - uses: actions/upload-artifact@v3
        with:
          name: testapp-apk
          path: testapp/build/outputs/apk/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: obfuscator-aars
          path: obfuscator/build/outputs/aar/
          if-no-files-found: error
