name: Lint Android
on: [workflow_call]
jobs:
  lint-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: lint
        run: ./gradlew ktlintCheck
